// Include default chains here

import { Chain, ChainId } from "../types/chain";

export const CHAINS: Record<ChainId, Chain> = {
  [ChainId.Ethereum]: {
    id: ChainId.Ethereum,
    name: "Ethereum",
    rpcUrls: {
      default: {
        http: [""],
      },
    },
    nativeCurrency: {
      name: "Ether",
      symbol: "ETH",
      decimals: 18,
    },
    chainType: "public",
  },
  [ChainId.Polygon]: {
    id: 137,
    name: "Polygon",
    rpcUrls: undefined,
    nativeCurrency: {
      name: "",
      symbol: "",
      decimals: 0,
    },
    testnet: undefined,
    blockExplorers: undefined,
    blockTime: undefined,
    chainType: "public",
    network: undefined,
    averageBlockTime: undefined,
    finalitySeconds: undefined,
  },
  [ChainId.BSC]: {
    id: 112,
    name: "Binance",
    rpcUrls: undefined,
    nativeCurrency: {
      name: "",
      symbol: "",
      decimals: 0,
    },
    testnet: undefined,
    blockExplorers: undefined,
    blockTime: undefined,
    chainType: "public",
    network: undefined,
    averageBlockTime: undefined,
    finalitySeconds: undefined,
  },
  [ChainId.Avalanche]: {
    id: 445,
    name: "Avalanche",
    rpcUrls: undefined,
    nativeCurrency: {
      name: "",
      symbol: "",
      decimals: 0,
    },
    testnet: undefined,
    blockExplorers: undefined,
    blockTime: undefined,
    chainType: "public",
    network: undefined,
    averageBlockTime: undefined,
    finalitySeconds: undefined,
  },
  [ChainId.Arbitrum]: {
    id: 3384,
    name: "Arbitrum",
    rpcUrls: undefined,
    nativeCurrency: {
      name: "",
      symbol: "",
      decimals: 0,
    },
    testnet: undefined,
    blockExplorers: undefined,
    blockTime: undefined,
    chainType: "public",
    network: undefined,
    averageBlockTime: undefined,
    finalitySeconds: undefined,
  },
  [ChainId.Optimism]: {
    id: 34,
    name: "Optimism",
    rpcUrls: undefined,
    nativeCurrency: {
      name: "",
      symbol: "",
      decimals: 0,
    },
    testnet: undefined,
    blockExplorers: undefined,
    blockTime: undefined,
    chainType: "public",
    network: undefined,
    averageBlockTime: undefined,
    finalitySeconds: undefined,
  },
  [ChainId.Base]: {
    id: 13378,
    name: "Base",
    rpcUrls: undefined,
    nativeCurrency: {
      name: "",
      symbol: "",
      decimals: 0,
    },
    testnet: undefined,
    blockExplorers: undefined,
    blockTime: undefined,
    chainType: "consortium",
    network: undefined,
    averageBlockTime: undefined,
    finalitySeconds: undefined,
  },
  [ChainId.CorpDevnet]: {
    id: 7758474,
    name: "CorpDevnet",
    rpcUrls: undefined,
    nativeCurrency: {
      name: "",
      symbol: "",
      decimals: 0,
    },
    testnet: undefined,
    blockExplorers: undefined,
    blockTime: undefined,
    chainType: "consortium",
    network: undefined,
    averageBlockTime: undefined,
    finalitySeconds: undefined,
  },
  [ChainId.ResearchNet]: {
    id: 22838,
    name: "ResearchNet",
    rpcUrls: undefined,
    nativeCurrency: {
      name: "",
      symbol: "",
      decimals: 0,
    },
    testnet: undefined,
    blockExplorers: undefined,
    blockTime: undefined,
    chainType: "private",
    network: undefined,
    averageBlockTime: undefined,
    finalitySeconds: undefined,
  },
};
